### ISSUE TITLE
Issue with sample files - Local variable 'combs' referenced before assignment.

### ISSUE THREAD

**Issue by giovanniconsiglio** [ladybug-analysis-tools/honeybee-grasshopper#103]
Hi All,

I'm getting a error in the "Annual Daylight Metrics" node of the sample file 06_daylight_coefficient_gridbased. 

![image](https://user-images.githubusercontent.com/37558888/60012682-e09ce300-967c-11e9-8a6d-1fe30327da86.png)
 
ERROR:
	Local variable 'combs' referenced before assignment.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/honeybee-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Users\giovanni\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\Honeybee\extra\honeybee\radiance\analysisgrid.py", line 739, in parse_blind_states
    return self.analysis_points[0].parse_blind_states(blinds_state_ids)
  File "C:\Users\giovanni\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\Honeybee\extra\honeybee\radiance\analysispoint.py", line 945, in parse_blind_states
    return combs
UnboundLocalError: Local variable 'combs' referenced before assignment.

I got similar errors with other nodes in others sample file. What I'm doing wrong?

Many thanks,

Regards,
Giovanni

**Comment by mostaphaRoudsari** [comment]
Thank you for reporting this. The Dynamo packages need some real attention. I'll address the issue when we update the packages.

**Comment by punderscoresmithuk** [comment]
Is anyone aware of a workaround?
