### ISSUE TITLE
 invalid literal for float(): DynamoForRevit

### ISSUE THREAD

**Issue by Monica-Xiao** [ladybug-analysis-tools/honeybee-grasshopper#107]
Hello! Thank you for helping us by reporting bugs or requesting for improvements. Before posting your issue, please quickly review the notes below to ensure opening an issue is the right choice for your case.

- If this issue is **not** a bug report or improvement request, please check the [Ladybug Tools forum](http://discourse.ladybug.tools), and start a topic there to discuss your issue. If you don't have an account on our forum, you can ask for one as noted in [this post](http://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8).

- If this issue is related to the Ladybug + Honeybee legacy plugins for Grasshopper, please post it to the repositories for legacy versions: [Ladybug](https://github.com/mostaphaRoudsari/ladybug), [honeybee](https://github.com/mostaphaRoudsari/honeybee). If you're not sure whether you are using the legacy Ladybug + Honeybee, see [here](http://www.ladybug.tools/about.html#14).

- If this issue is for any of the new Plus plugins, please ensure this is the correct repository for your issue. Issues that are specific to the plugin interface should be posted to the correct plugin repository. For example issues related to the Honeybee plugin for Dynamo should be posted to [honeybee-dynamo](https://github.com/ladybug-tools/honeybee-dynamo/) repository and not [honeybee](https://github.com/ladybug-tools/honeybee/).

- Finally, if you haven't done it already, please do a quick search of our existing issues and ensure that the issue has not already been posted.

If you passed all the checks above, feel free to post your issue and please respect these guidelines:
- Be clear about the error and include related information about how to re-create the issue.
- If possible, share an example file or example code for us to recreate the issue.

Thank you again for opening an issue. This will benefit all our users! ALSO DO NOT FORGET TO REMOVE ALL THESE NOTES BEFORE POSTING YOUR ISSUE.

**Comment by Monica-Xiao** [comment]
hi, I am recently starting to use Honeybee in Dynamo for light analysis. No matter in my own project or in the honeybee sample projects, I have the same problems for all the honeybee nodes, it says:

invalid literal for float(): DynamoForRevit
Traceback (most recent call last):
    File "<string>", line 48, in <module>
    File "<string>", line 16, in tryGetPluginPath
ValueError: invalid literal for float(): DynamoForRevit
![image](https://user-images.githubusercontent.com/54935139/64328719-ef066400-d008-11e9-8cd8-ae755a1a2818.png)


then I opened one node called "Room to HBZones" and its "import and prepare py code" node, and find that there is nothing at line 16, only a start of "if" function at line 48, which made me confused.

I installed the honeybee package and ladybug package through the packages manager in the dynamo itself. And my dynamo vision is 2.1, is it the problem?

**Comment by RasmusNH** [comment]
Anyone who has an answer for this issue? I got a similar issue.

**Comment by adonis8233** [comment]
> Anyone who has an answer for this issue? I got a similar issue.

I have this issue too!

**Comment by adonis8233** [comment]
> Anyone who has an answer for this issue? I got a similar issue.

Did you solve it yet?

**Comment by rogers53** [comment]
I have the same problem ...

**Comment by ugepirate01** [comment]
I have the same problem as well.  

We just installed the packages and openfoam to start learning Ladybug/Butterfly.

**Comment by JChung-rpi** [comment]
I have the same problem..:(

**Comment by anyinye** [comment]
Same here!
