### ISSUE TITLE
Could not CHMOD executable

### ISSUE THREAD

**Issue by flanaganthemanagan** [ladybug-analysis-tools/honeybee-grasshopper#98]
Trying to perform a Solar Access Radiance Analysis on façade components. Following ERRReport is generated:

Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "C:\Users\Student\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\solaraccess\gridbased.py", line 341, in write
    oc = Oconv(project_name)
  File "C:\Users\Student\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\oconv.py", line 62, in __init__
    RadianceCommand.__init__(self)
  File "C:\Users\Student\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 19, in __init__
    self.radbin_path = config.radbin_path
  File "C:\Users\Student\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 53, in radbin_path
    self.__check_executable(radbin_path=path, raise_exception=True)
  File "C:\Users\Student\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 157, in _RadianceCommand__check_executable
    raise ValueError('Could not CHMOD executable: {}'.format(errmsg))
ValueError: Could not CHMOD executable: [Errno 2] file does not exist: oconv.exe

![image](https://user-images.githubusercontent.com/47898524/53260951-b76a4700-36ca-11e9-8f4a-967928d0d250.png)

**Comment by ManiakManiak** [comment]
You have to instal radiance software at: C:\radiance

**Comment by flanaganthemanagan** [comment]
Thank you!
